name: Cache Vite and npm
description: Set up Node.js with npm cache and restore Vite build cache.
inputs:
  node-version:
    description: Node.js version to use
    required: true
runs:
  using: composite
  steps:
    - name: Setup Node.js (with npm cache)
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.2.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: "npm"
        cache-dependency-path: |
          package-lock.json

    - name: Cache Vite build cache
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
      with:
        path: |
          node_modules/.vite
          client/node_modules/.vite
        key: vite-cache-${{ runner.os }}-${{ inputs.node-version }}-${{ hashFiles('package-lock.json', 'vite.config.ts') }}
        restore-keys: |
          vite-cache-${{ runner.os }}-${{ inputs.node-version }}-
