name: Cache Vite and npm
description: Set up Node.js with npm cache and restore Vite build cache.
inputs:
  node-version:
    description: Node.js version to use
    required: true
runs:
  using: composite
  steps:
    - name: Setup Node.js (with npm cache)
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: "npm"

    - name: Cache Vite build cache
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        path: |
          node_modules/.vite
          client/node_modules/.vite
        key: vite-cache-${{ runner.os }}-${{ inputs.node-version }}-${{ hashFiles('package-lock.json', 'vite.config.ts', 'client/vite.config.ts') }}
        restore-keys: |
          vite-cache-${{ runner.os }}-${{ inputs.node-version }}-
